packages:
  - "apps/*"
  - "packages/*"
catalog:
  better-auth: 1.4.10
  dotenv: ^17.2.2
  next: ^16.1.1
  react: ^19.2.3
  "react-dom": ^19.2.3
  "@types/react": ^19.2.3
  "@types/react-dom": ^19.2.3
  typescript: ^5
  zod: ^4.1.13
